
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tf-runner-role
  namespace: default
rules:
  # Secrets needed for TLS, TF state, outputs, varsFrom, etc.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # ConfigMaps (some modules or backend configs may use them)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


  # Events: helpful for status reporting
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  # 🔒 Leases: required for lock acquisition during init/plan/apply
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

