apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-aws-permissions
  namespace: default
spec:
  destroyResourcesOnDeletion: true
  # Reconcile cadence: plan/apply and drift detection cadence
  interval: 5m

  # Automate plan approval + apply (good for non-prod; for prod consider manual)
  approvePlan: auto

  # Path within the GitRepository that contains your Terraform code
  path: terraform/access-entry-creator
  runnerPodTemplate:
    spec:
      image: 810918108393.dkr.ecr.eu-south-1.amazonaws.com/tf-runner-tools:v1

  # Reference to the Flux Source
  sourceRef:
    kind: GitRepository
    name: ack-git

  # Runner configuration (multi-tenancy model)
  serviceAccountName: tf-runner-sa
  vars:
    - name: region
      value: "eu-south-1"
    - name: eks_cluster_name
      value: "k8-simulation-client"
    - name: runner_principal_arn
      value: "arn:aws:iam::810918108393:role/eksctl-k8-simulation-nodegroup-def-NodeInstanceRole-WrSOfoyc7m3b"

---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-token-writer-v2
  namespace: default # Or your Flux namespace
spec:
  destroyResourcesOnDeletion: true
  # This is the most critical part. It tells Flux to wait until
  # the first stage is successfully applied.
  dependsOn:
    - name: tf-aws-permissions

  # Reconcile cadence: plan/apply and drift detection cadence
  interval: 5m

  # Automate plan approval + apply (good for non-prod; for prod consider manual)
  approvePlan: auto

  # Path within the GitRepository that contains your Terraform code
  path: terraform/token-writer
  runnerPodTemplate:
    spec:
      image: 810918108393.dkr.ecr.eu-south-1.amazonaws.com/tf-runner-tools:v1

  # Reference to the Flux Source
  sourceRef:
    kind: GitRepository
    name: ack-git

  # Runner configuration (multi-tenancy model)
  serviceAccountName: tf-runner-sa

  # Define all your variables for this stage here
  vars:
    - name: region
      value: "eu-south-1"
    - name: eks_cluster_name
      value: "k8-simulation-client"
    - name: runner_principal_arn
      value: "arn:aws:iam::810918108393:role/eksctl-k8-simulation-nodegroup-def-NodeInstanceRole-WrSOfoyc7m3b"
    - name: remote_target_namespace
      value: "default"
    - name: publish_secret_namespace
      value: "default"

---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-kubeconfig-builder-v2
  namespace: default # Or your Flux namespace
spec:
  destroyResourcesOnDeletion: true
  # This is the most critical part. It tells Flux to wait until
  # the first stage is successfully applied.
  dependsOn:
    - name: tf-token-writer-v2
  
  # Reconcile cadence: plan/apply and drift detection cadence
  interval: 5m

  # Automate plan approval + apply (good for non-prod; for prod consider manual)
  approvePlan: auto

  # Path within the GitRepository that contains your Terraform code
  path: terraform/kubeconfig-builder
  runnerPodTemplate:
    spec:
      image: 810918108393.dkr.ecr.eu-south-1.amazonaws.com/tf-runner-tools:v1

  # Reference to the Flux Source
  sourceRef:
    kind: GitRepository
    name: ack-git

  # Runner configuration (multi-tenancy model)
  serviceAccountName: tf-runner-sa

  # Define variables for this stage
  vars:
    - name: publish_secret_namespace
      value: "default"
    - name: publish_secret_name
      value: "tf-remote-kubeconfig-secret" # The final secret for your HelmRelease
