apiVersion: batch/v1
kind: Job
metadata:
  name: helm-release-wait
  annotations:
    "helm.sh/hook": pre-install
    # Optional: also run on upgrade
    # "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    # Clean up after success or failure (adjust as needed)
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 0
  template:
    metadata:
      name: helm-release-wait
    spec:
      # optional: set to the release namespace explicitly
      # nodeSelector, tolerations, affinity can be added if needed
      restartPolicy: Never
      serviceAccountName: default
      containers:
        - name: wait
          image: busybox:1.36.1
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo 'Pre-install wait: 5 minutes' && sleep 300"]
